import React from "react";
import { HashRouter as Router, Routes, Route, Navigate } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "sonner";

import { AuthProvider, useAuth } from "./contexts/AuthContext";

import { LoginPage } from "./components/LoginPage";
import { DashboardLayout } from "./components/DashboardLayout";
import { Dashboard } from "./components/Dashboard";
import { PatientManagement } from "./components/PatientManagement";
import { PatientProfile } from "./components/PatientProfile";
import { FoodDatabase } from "./components/FoodDatabase";
import { DietPlans } from "./components/DietPlans";
import { Reports } from "./components/Reports";
import { Settings } from "./components/Settings";

// Doctor-specific components
import { Collections } from "./components/Collections";
import { Recipes } from "./components/Recipes";
import DietChart from "./components/DietChart";
import { AutoGenerateDiet } from "./components/AutoGenerateDiet";
import { ChatWithPatients } from "./components/ChatWithPatients";
import { CreateDietPlans } from "./components/CreateDietPlans";

// Patient-specific components
import { DietHistory } from "./components/DietHistory";
import { ChatWithDoctor } from "./components/ChatWithDoctor";
import { Reminders } from "./components/Reminders";
import { PatientSettings } from "./components/PatientSettings";

// Admin components
import { AdminDashboard } from "./components/AdminDashboard";
import { DoctorVerificationPage } from "./components/DoctorVerificationPage";
import AyurvedicFoodGenerator from "./components/AyurvedicFoodGenerator";

// React Query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000,
      retry: 1,
    },
  },
});

// Error Boundary
class ErrorBoundary extends React.Component<
  {},
  { hasError: boolean }
> {
  constructor(props: {}) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  componentDidCatch(error: any, info: any) {
    console.error("Error Boundary:", error, info);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen flex items-center justify-center">
          <div className="text-center">
            <h2 className="text-xl mb-2">Something went wrong</h2>
            <button
              className="px-4 py-2 bg-primary text-white"
              onClick={() => window.location.reload()}
            >
              Refresh
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

// -------------------------
// MAIN APP CONTENT
// -------------------------
function AppContent() {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-muted-foreground text-center">
          <div className="animate-spin h-10 w-10 border-2 border-primary border-b-transparent rounded-full mx-auto mb-4"></div>
          Loading...
        </div>
      </div>
    );
  }

  // Not logged in → show login page
  if (!isAuthenticated) {
    return <LoginPage />;
  }

  // Logged in → load dashboard
  return (
    <ErrorBoundary>
      <DashboardLayout>
        <Routes>
          <Route path="/" element={<Navigate to="/dashboard" replace />} />
          <Route path="/food-generator" element={<AyurvedicFoodGenerator />} />

          {/* Common Routes */}
          <Route path="/dashboard" element={<Dashboard />} />
          <Route path="/reports" element={<Reports />} />
          <Route path="/settings" element={<Settings />} />
          <Route path="/patient-settings" element={<PatientSettings />} />

          {/* Admin Routes */}
          <Route path="/admin/dashboard" element={<AdminDashboard />} />
          <Route path="/admin/doctors" element={<DoctorVerificationPage />} />

          {/* Doctor Routes */}
          <Route path="/patients" element={<PatientManagement />} />
          <Route path="/patients/:id" element={<PatientProfile />} />
          <Route path="/collections" element={<Collections />} />
          <Route path="/recipes" element={<Recipes />} />
          <Route path="/diet-chart" element={<DietChart />} />
          <Route path="/diet-plans" element={<DietPlans />} />
          <Route path="/create-diet-plans" element={<CreateDietPlans />} />
          <Route path="/auto-generate" element={<AutoGenerateDiet />} />
          <Route path="/food-database" element={<FoodDatabase />} />
          <Route path="/chat-doctor" element={<ChatWithPatients />} />
          <Route
            path="/doctor/pending"
            element={
              <div className="p-8 text-center">
                Your account is pending verification.
              </div>
            }
          />

          {/* Patient Routes */}
          <Route path="/diet-history" element={<DietHistory />} />
          <Route path="/chat" element={<ChatWithDoctor />} />
          <Route path="/reminders" element={<Reminders />} />

          {/* Fallback */}
          <Route path="*" element={<Navigate to="/dashboard" replace />} />
        </Routes>
      </DashboardLayout>
    </ErrorBoundary>
  );
}

// -------------------------
// ROOT APP COMPONENT
// -------------------------
export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Router>
        {/* Router MUST wrap AuthProvider + LoginPage */}
        <AuthProvider>
          <AppContent />
          <Toaster position="top-right" />
        </AuthProvider>
      </Router>
    </QueryClientProvider>
  );
}
