import { HashRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Toaster } from 'sonner';
import { AuthProvider, useAuth } from './contexts/AuthContext';

import { LoginPage } from './components/LoginPage';
import { DashboardLayout } from './components/DashboardLayout';
import { Dashboard } from './components/Dashboard';
import { PatientManagement } from './components/PatientManagement';
import { PatientProfile } from './components/PatientProfile';
import { FoodDatabase } from './components/FoodDatabase';
import { DietPlans } from './components/DietPlans';
import { Reports } from './components/Reports';
import { Settings } from './components/Settings';
import { Collections } from './components/Collections';
import { Recipes } from './components/Recipes';
import { DietChart } from './components/DietChart';
import { AutoGenerateDiet } from './components/AutoGenerateDiet';
import { ChatWithPatients } from './components/ChatWithPatients';
import { DietHistory } from './components/DietHistory';
import { ChatWithDoctor } from './components/ChatWithDoctor';
import { Reminders } from './components/Reminders';
import { PatientSettings } from './components/PatientSettings';

// Query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000,
      retry: 1,
    },
  },
});

// Error boundary
function ErrorBoundaryWrapper({ children }) {
  return children;
}

function AppContent() {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p>Loading...</p>
      </div>
    );
  }

  if (!isAuthenticated) {
    return <LoginPage />;
  }

  return (
    <Router>
      <DashboardLayout>
        <Routes>
          <Route path="/" element={<Navigate to="/dashboard" replace />} />
          <Route path="/dashboard" element={<Dashboard />} />

          {/* Doctor */}
          <Route path="/patients" element={<PatientManagement />} />
          <Route path="/patients/:id" element={<PatientProfile />} />
          <Route path="/collections" element={<Collections />} />
          <Route path="/recipes" element={<Recipes />} />
          <Route path="/diet-chart" element={<DietChart />} />
          <Route path="/auto-generate" element={<AutoGenerateDiet />} />
          <Route path="/food-database" element={<FoodDatabase />} />
          <Route path="/chat-doctor" element={<ChatWithPatients />} />

          {/* Patient */}
          <Route path="/diet-history" element={<DietHistory />} />
          <Route path="/chat" element={<ChatWithDoctor />} />
          <Route path="/reminders" element={<Reminders />} />

          {/* Shared */}
          <Route path="/reports" element={<Reports />} />
          <Route path="/settings" element={<Settings />} />
          <Route path="/patient-settings" element={<PatientSettings />} />

          <Route path="*" element={<Navigate to="/dashboard" replace />} />
        </Routes>
      </DashboardLayout>
    </Router>
  );
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <ErrorBoundaryWrapper>
          <AppContent />
          <Toaster position="top-right" />
        </ErrorBoundaryWrapper>
      </AuthProvider>
    </QueryClientProvider>
  );
}
