import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card";
import { Button } from "./ui/button";
import { Label } from "./ui/label";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "./ui/select";
import { RefreshCw, Target, Wand2, Download, User, Calendar } from "lucide-react";

export function AutoGenerateDiet() {
  // Patient details state
  const [patientName, setPatientName] = useState("");
  const [patientAge, setPatientAge] = useState("");
  const [patientGender, setPatientGender] = useState("Male");
  const [doctorName, setDoctorName] = useState("Dr. Ayurvedic Consultant");

  // Diet parameters state
  const [prakriti, setPrakriti] = useState("Vata");
  const [dosha, setDosha] = useState("none");
  const [calories, setCalories] = useState(2000);
  const [isGenerating, setIsGenerating] = useState(false);
  const [diet, setDiet] = useState<any | null>(null);

  // --------------------- GENERATE DIET ---------------------
  const handleGenerate = async () => {
    if (!prakriti) {
      alert("Please select prakriti");
      return;
    }

    setIsGenerating(true);
    setDiet(null);

    try {
      const AI_API_URL = import.meta.env.VITE_AI_API_URL || "http://localhost:8000";
      const res = await fetch(`${AI_API_URL}/generate-diet`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prakriti,
          dosha: dosha === "none" ? "" : dosha,
          daily_calorie_target: calories,
        }),
      });

      const data = await res.json();
      setDiet(data.diet_plan);
    } catch (err) {
      console.error(err);
      alert("Failed to generate diet plan. Please check if AI backend is running.");
    } finally {
      setIsGenerating(false);
    }
  };

  // Helper to format food name and remove unprintable Devanagari glyphs in standard jsPDF
  const getFoodDisplayName = (item: any) => {
    let name = item.food || "";
     // Clean up any unrenderable Unicode characters so jsPDF doesn't produce garbled symbols
     return name.replace(/[\u0900-\u097F]/g, "").replace(/\(\s*\)/g, "").trim();
  };

  // --------------------- PDF DOWNLOAD ---------------------
  const handleDownloadPDF = () => {
    if (!diet) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header Background banner
    doc.setFillColor(34, 112, 67); // Ayurvedic Green
    doc.rect(0, 0, pageWidth, 24, "F");

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(255, 255, 255);
    doc.text("AYURCARE - 7-DAY AYURVEDIC DIET PLAN", 14, 16);

    // Patient & Doctor Info Box
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("PATIENT & CLINICAL DETAILS", 14, 32);

    doc.setDrawColor(210, 210, 210);
    doc.setFillColor(248, 250, 248);
    doc.roundedRect(14, 35, pageWidth - 28, 24, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    
    // Column 1
    doc.text(`Patient Name: ${patientName || "N/A"}`, 18, 42);
    doc.text(`Age / Gender: ${patientAge ? `${patientAge} yrs` : "N/A"} / ${patientGender}`, 18, 49);
    doc.text(`Consultant: ${doctorName}`, 18, 55);

    // Column 2
    doc.text(`Prakriti (Constitution): ${prakriti}`, 110, 42);
    doc.text(`Dosha Imbalance: ${dosha === "none" ? "None (Balanced)" : dosha}`, 110, 49);
    doc.text(`Daily Calorie Target: ${calories} kcal/day`, 110, 55);

    let startY = 66;

    // Render 7 Days
    Object.entries(diet).forEach(([day, meals]: any) => {
      if (startY > 225) {
        doc.addPage();
        startY = 20;
      }

      // Day Title Header
      doc.setFillColor(235, 244, 238);
      doc.roundedRect(14, startY - 4, pageWidth - 28, 8, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(34, 112, 67);
      doc.text(`DAY ${day} SCHEDULE`, 18, startY + 2);
      startY += 8;

      ["breakfast", "lunch", "dinner"].forEach((mealType) => {
        const rows = meals[mealType].map((item: any) => [
          getFoodDisplayName(item),
          item.rasa || "-",
           `${Math.round(item.calories || 0)} kcal`,
          `${Number(item.protein || 0).toFixed(1)}g`,
          `${Number(item.carbs || 0).toFixed(1)}g`,
          `${Number(item.fat || 0).toFixed(1)}g`,
        ]);

        autoTable(doc, {
          startY,
          head: [[mealType.toUpperCase(), "RASA", "ENERGY", "PROTEIN", "CARBS", "FAT"]],
          body: rows,
          theme: "grid",
          headStyles: { fillColor: [34, 112, 67], textColor: 255, fontSize: 8, fontStyle: "bold" },
          bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
          columnStyles: {
            0: { cellWidth: 70 }, // Food Name + Hindi
            1: { cellWidth: 25 }, // Rasa
          },
          margin: { left: 14, right: 14 },
        });

        // @ts-ignore
        startY = doc.lastAutoTable.finalY + 4;
      });

      // Day Nutrition Totals Summary
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(50, 50, 50);
      const totalCal = Math.round(meals.totals.calories || 0).toFixed(1);
      const totalProt = Number(meals.totals.protein || 0).toFixed(1);
      const totalCarb = Number(meals.totals.carbs || 0).toFixed(1);
      const totalFat = Number(meals.totals.fat || 0).toFixed(1);

      doc.text(
        `Day ${day} Totals: ${totalCal} kcal | Protein: ${totalProt}g | Carbs: ${totalCarb}g | Fat: ${totalFat}g`,
        16,
        startY + 2
      );

      startY += 10;
    });

    // Save with patient name if provided
    const safeName = patientName ? patientName.trim().replace(/\s+/g, "_") : "Patient";
    doc.save(`Ayurcare_Diet_Plan_${safeName}.pdf`);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-semibold">Auto Generate Diet Plan</h1>
          <p className="text-muted-foreground">
            Personalized 7-day Ayurvedic nutrition plan with patient details and PDF export.
          </p>
        </div>
        <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
          <Wand2 className="w-6 h-6 text-primary" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Patient Details Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <User className="w-5 h-5 mr-2 text-primary" />
              Patient Details
            </CardTitle>
            <CardDescription>Include recipient information in the report.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1">
              <Label>Patient Full Name</Label>
              <input
                type="text"
                placeholder="e.g. Rahul Sharma"
                value={patientName}
                onChange={(e) => setPatientName(e.target.value)}
                className="w-full border rounded-md px-3 py-2 text-sm"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>Age</Label>
                <input
                  type="number"
                  placeholder="e.g. 35"
                  value={patientAge}
                  onChange={(e) => setPatientAge(e.target.value)}
                  className="w-full border rounded-md px-3 py-2 text-sm"
                />
              </div>

              <div className="space-y-1">
                <Label>Gender</Label>
                <Select value={patientGender} onValueChange={setPatientGender}>
                  <SelectTrigger>
                    <SelectValue placeholder="Gender" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Male">Male</SelectItem>
                    <SelectItem value="Female">Female</SelectItem>
                    <SelectItem value="Other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-1">
              <Label>Doctor / Consultant Name</Label>
              <input
                type="text"
                value={doctorName}
                onChange={(e) => setDoctorName(e.target.value)}
                className="w-full border rounded-md px-3 py-2 text-sm"
              />
            </div>
          </CardContent>
        </Card>

        {/* Ayurvedic Parameters Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <Target className="w-5 h-5 mr-2 text-primary" />
              Ayurvedic Configuration
            </CardTitle>
            <CardDescription>Select prakriti, dosha imbalance, and calories.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1">
              <Label>Prakriti (Constitution)</Label>
              <Select value={prakriti} onValueChange={setPrakriti}>
                <SelectTrigger>
                  <SelectValue placeholder="Select prakriti" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Vata">Vata</SelectItem>
                  <SelectItem value="Pitta">Pitta</SelectItem>
                  <SelectItem value="Kapha">Kapha</SelectItem>
                  <SelectItem value="Vata-Pitta">Vata-Pitta</SelectItem>
                  <SelectItem value="Vata-Kapha">Vata-Kapha</SelectItem>
                  <SelectItem value="Pitta-Kapha">Pitta-Kapha</SelectItem>
                  <SelectItem value="Vata-Pitta-Kapha">Vata-Pitta-Kapha</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label>Dosha Imbalance</Label>
              <Select value={dosha} onValueChange={setDosha}>
                <SelectTrigger>
                  <SelectValue placeholder="Select imbalance" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">None / Balanced</SelectItem>
                  <SelectItem value="V">Vata (V)</SelectItem>
                  <SelectItem value="P">Pitta (P)</SelectItem>
                  <SelectItem value="K">Kapha (K)</SelectItem>
                  <SelectItem value="VP">Vata + Pitta</SelectItem>
                  <SelectItem value="VK">Vata + Kapha</SelectItem>
                  <SelectItem value="PK">Pitta + Kapha</SelectItem>
                  <SelectItem value="VPK">Vata + Pitta + Kapha</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label>Daily Calorie Target (kcal)</Label>
              <input
                type="number"
                min={1200}
                max={3500}
                value={calories}
                onChange={(e) => setCalories(Number(e.target.value))}
                className="w-full border rounded-md px-3 py-2 text-sm"
              />
            </div>

            <Button className="w-full mt-2" onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating AI Diet Plan…
                </>
              ) : (
                <>
                  <Target className="w-4 h-4 mr-2" />
                  Generate 7-Day Diet
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Generated Diet Results */}
      {diet && (
        <Card>
          <CardHeader className="flex flex-row justify-between items-center">
            <div>
              <CardTitle>Generated 7-Day Ayurvedic Diet Plan</CardTitle>
              <CardDescription>
                Ready for {patientName || "Patient"} &bull; {prakriti} constitution &bull; {calories} kcal/day
              </CardDescription>
            </div>
            <Button onClick={handleDownloadPDF} className="bg-primary text-white">
              <Download className="w-4 h-4 mr-2" />
              Download Clinical PDF
            </Button>
          </CardHeader>
          <CardContent className="space-y-6">
            {Object.entries(diet).map(([day, meals]: any) => (
              <div key={day} className="border rounded-lg p-5 bg-card">
                <h2 className="text-xl font-semibold text-primary">Day {day}</h2>

                {["breakfast", "lunch", "dinner"].map((mealKey) => (
                  <div key={mealKey} className="mt-4">
                    <h3 className="font-medium capitalize text-sm text-muted-foreground">{mealKey}</h3>
                    <div className="bg-muted p-3 rounded-md space-y-1.5 mt-1">
                      {meals[mealKey].map((item: any, idx: number) => (
                        <div key={idx} className="flex justify-between items-center text-sm">
                          <span className="font-medium">
                            • {getFoodDisplayName(item)}
                            {item.rasa && (
                              <span className="ml-2 text-xs px-2 py-0.5 bg-primary/10 rounded-full text-primary">
                                {item.rasa}
                              </span>
                            )}
                          </span>
                          <span className="text-xs text-muted-foreground">
                            {item.calories} kcal &bull; P:{item.protein}g C:{item.carbs}g F:{item.fat}g
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}

                <div className="bg-primary/10 p-3 mt-4 rounded-md flex justify-between items-center">
                  <span className="font-semibold text-xs text-primary">DAILY TOTALS</span>
                  <span className="text-xs font-semibold">
                    Calories: {Math.round(meals.totals.calories)} kcal &bull; Protein: {Number(meals.totals.protein).toFixed(1)}g &bull; Carbs: {Number(meals.totals.carbs).toFixed(1)}g &bull; Fat: {Number(meals.totals.fat).toFixed(1)}g
                  </span>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}


// import React, { useState } from "react";
// import jsPDF from "jspdf";
// import autoTable from "jspdf-autotable";
// import {
//   Card,
//   CardContent,
//   CardDescription,
//   CardHeader,
//   CardTitle,
// } from "./ui/card";
// import { Button } from "./ui/button";
// import { Label } from "./ui/label";
// import {
//   Select,
//   SelectTrigger,
//   SelectValue,
//   SelectContent,
//   SelectItem,
// } from "./ui/select";
// import { RefreshCw, Target, Wand2, Download, User, Calendar} from "lucide-react";

// export function AutoGenerateDiet() {
//   const [prakriti, setPrakriti] = useState("");
//   const [dosha, setDosha] = useState("none");
//   const [calories, setCalories] = useState(2000);
//   const [isGenerating, setIsGenerating] = useState(false);
//   const [diet, setDiet] = useState<any | null>(null);

//   // --------------------- GENERATE DIET ---------------------
//   const handleGenerate = async () => {
//     if (!prakriti) {
//       alert("Please select prakriti");
//       return;
//     }

//     setIsGenerating(true);
//     setDiet(null);

//     try {
//       const AI_API_URL = import.meta.env.VITE_AI_API_URL || "http://localhost:8000";
//       const res = await fetch(`${AI_API_URL}/generate-diet`, {
//         method: "POST",
//         headers: { "Content-Type": "application/json" },
//         body: JSON.stringify({
//           prakriti,
//           dosha: dosha === "none" ? "" : dosha,
//           daily_calorie_target: calories,
//         }),
//       });

//       const data = await res.json();
//       console.log("API response:", data);

//       setDiet(data.diet_plan); // IMPORTANT: use diet_plan not diet
//     } catch (err) {
//       console.error(err);
//       alert("Failed to generate diet plan");
//     } finally {
//       setIsGenerating(false);
//     }
//   };

//   // --------------------- PDF DOWNLOAD ---------------------
//   const handleDownloadPDF = () => {
//     if (!diet) return;

//     const doc = new jsPDF();
//     doc.setFont("helvetica", "bold");
//     doc.setFontSize(18);
//     doc.text("7-Day Ayurvedic Diet Plan", 14, 20);

//     doc.setFont("helvetica", "normal");
//     doc.setFontSize(12);
//     doc.text(`Prakriti: ${prakriti}`, 14, 30);
//     doc.text(`Dosha: ${dosha === "none" ? "None" : dosha}`, 14, 38);
//     doc.text(`Calories: ${calories} kcal/day`, 14, 46);

//     let startY = 55;

//     Object.entries(diet).forEach(([day, meals]: any) => {
//       if (startY > 250) {
//         doc.addPage();
//         startY = 20;
//       }

//       doc.setFont("helvetica", "bold");
//       doc.setFontSize(14);
//       doc.text(`Day ${day}`, 14, startY);
//       startY += 6;

//       ["breakfast", "lunch", "dinner"].forEach((mealType) => {
//         const rows = meals[mealType].map((item: any) => [
//           item.food,
//           `${item.calories} kcal`,
//           `${item.protein}g`,
//           `${item.carbs}g`,
//           `${item.fat}g`,
//         ]);

//         autoTable(doc, {
//           startY,
//           head: [[mealType.toUpperCase(), "KCAL", "P", "C", "F"]],
//           body: rows,
//           theme: "grid",
//           headStyles: { fillColor: [40, 80, 60], textColor: 255, fontSize: 10 },
//           bodyStyles: { fontSize: 9 },
//           margin: { left: 14, right: 14 },
//         });

//         // @ts-ignore
//         startY = doc.lastAutoTable.finalY + 6;
//       });

//       doc.setFont("helvetica", "bold");
//       doc.setFontSize(11);
//       doc.text(
//         `Totals: ${meals.totals.calories} kcal | P:${meals.totals.protein}g | C:${meals.totals.carbs}g | F:${meals.totals.fat}g`,
//         14,
//         startY
//       );

//       startY += 12;
//     });

//     doc.save("ayurvedic_diet_plan.pdf");
//   };

//   return (
//     <div className="space-y-8">
//       {/* Header */}
//       <div className="flex justify-between items-center">
//         <div>
//           <h1 className="text-3xl font-semibold">Auto Generate Diet</h1>
//           <p className="text-muted-foreground">
//             7-day personalized Ayurvedic diet based on prakriti & dosha.
//           </p>
//         </div>
//         <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
//           <Wand2 className="w-6 h-6 text-primary" />
//         </div>
//       </div>

//       {/* Input Card */}
//       <Card>
//         <CardHeader>
//           <CardTitle>Configuration</CardTitle>
//           <CardDescription>
//             Choose prakriti, imbalance, and calorie target.
//           </CardDescription>
//         </CardHeader>
//         <CardContent className="space-y-6">
//           {/* Prakriti */}
//           <div className="space-y-2">
//             <Label>Prakriti</Label>
//             <Select value={prakriti} onValueChange={setPrakriti}>
//               <SelectTrigger>
//                 <SelectValue placeholder="Select prakriti" />
//               </SelectTrigger>
//               <SelectContent>
//                 <SelectItem value="Vata">Vata</SelectItem>
//                 <SelectItem value="Pitta">Pitta</SelectItem>
//                 <SelectItem value="Kapha">Kapha</SelectItem>
//                 <SelectItem value="Vata-Pitta">Vata-Pitta</SelectItem>
//                 <SelectItem value="Vata-Kapha">Vata-Kapha</SelectItem>
//                 <SelectItem value="Pitta-Kapha">Pitta-Kapha</SelectItem>
//                 <SelectItem value="Vata-Pitta-Kapha">Vata-Pitta-Kapha</SelectItem>
//               </SelectContent>
//             </Select>
//           </div>

//           {/* Dosha */}
//           <div className="space-y-2">
//             <Label>Dosha imbalance</Label>
//             <Select value={dosha} onValueChange={setDosha}>
//               <SelectTrigger>
//                 <SelectValue placeholder="Select imbalance" />
//               </SelectTrigger>
//               <SelectContent>
//                 <SelectItem value="none">None / General</SelectItem>
//                 <SelectItem value="V">Vata</SelectItem>
//                 <SelectItem value="P">Pitta</SelectItem>
//                 <SelectItem value="K">Kapha</SelectItem>
//                 <SelectItem value="VP">Vata + Pitta</SelectItem>
//                 <SelectItem value="VK">Vata + Kapha</SelectItem>
//                 <SelectItem value="PK">Pitta + Kapha</SelectItem>
//                 <SelectItem value="VPK">Vata + Pitta + Kapha</SelectItem>
//               </SelectContent>
//             </Select>
//           </div>

//           {/* Calories */}
//           <div className="space-y-2">
//             <Label>Daily calories</Label>
//             <input
//               type="number"
//               min={1200}
//               max={3500}
//               value={calories}
//               onChange={(e) => setCalories(Number(e.target.value))}
//               className="w-full border rounded-md px-3 py-2"
//             />
//           </div>

//           {/* Generate Button */}
//           <Button className="w-full" onClick={handleGenerate} disabled={isGenerating}>
//             {isGenerating ? (
//               <>
//                 <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
//                 Generating…
//               </>
//             ) : (
//               <>
//                 <Target className="w-4 h-4 mr-2" />
//                 Generate Diet
//               </>
//             )}
//           </Button>
//         </CardContent>
//       </Card>

//       {/* Output */}
//       {diet && (
//         <Card>
//           <CardHeader className="flex justify-between items-center">
//             <CardTitle>7-Day Diet Plan</CardTitle>
//             <Button onClick={handleDownloadPDF}>
//               <Download className="w-4 h-4 mr-2" />
//               Download PDF
//             </Button>
//           </CardHeader>
//           <CardContent className="space-y-6">
//             {Object.entries(diet).map(([day, meals]: any) => (
//               <div key={day} className="border rounded-lg p-4 bg-card">
//                 <h2 className="text-xl font-semibold">Day {day}</h2>

//                 {["breakfast", "lunch", "dinner"].map((mealKey) => (
//                   <div key={mealKey} className="mt-4">
//                     <h3 className="font-medium capitalize">{mealKey}</h3>
//                     <div className="bg-muted p-3 rounded-md space-y-1">
//                       {meals[mealKey].map((item: any, idx: number) => (
//                         <p key={idx} className="text-sm">
//                           • {item.food}{" "}
//                           <span className="text-xs text-muted-foreground">
//                             ({item.calories} kcal — P:{item.protein}g, C:{item.carbs}g, F:{item.fat}g)
//                           </span>
//                         </p>
//                       ))}
//                     </div>
//                   </div>
//                 ))}

//                 <div className="bg-primary/10 p-3 mt-4 rounded-md">
//                   <p className="font-semibold text-sm">
//                     Totals: {meals.totals.calories} kcal | P:
//                     {meals.totals.protein}g | C:{meals.totals.carbs}g | F:
//                     {meals.totals.fat}g
//                   </p>
//                 </div>
//               </div>
//             ))}
//           </CardContent>
//         </Card>
//       )}
//     </div>
//   );
// }
