import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { Textarea } from './ui/textarea';
import { 
  Wand2, 
  User, 
  Target, 
  Calendar, 
  Zap,
  Settings,
  Download,
  Save,
  RefreshCw,
  CheckCircle
} from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Label } from './ui/label';
import { Slider } from './ui/slider';
import { Switch } from './ui/switch';

const mockPatients = [
  { id: 1, name: "Rajesh Kumar", dosha: "Vata", age: 45, condition: "Weight Loss" },
  { id: 2, name: "Priya Sharma", dosha: "Pitta", age: 32, condition: "Digestive Issues" },
  { id: 3, name: "Amit Patel", dosha: "Kapha", age: 38, condition: "Low Energy" },
  { id: 4, name: "Sunita Devi", dosha: "Vata-Pitta", age: 28, condition: "Pregnancy" }
];

export function AutoGenerateDiet() {
  const [selectedPatient, setSelectedPatient] = useState('');
  const [duration, setDuration] = useState([30]);
  const [calories, setCalories] = useState([1800]);
  const [dietGoal, setDietGoal] = useState('');
  const [restrictions, setRestrictions] = useState('');
  const [includeSnacks, setIncludeSnacks] = useState(true);
  const [includeSuplements, setIncludeSupplements] = useState(false);
  const [mealComplexity, setMealComplexity] = useState('medium');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedPlan, setGeneratedPlan] = useState(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate API call
    setTimeout(() => {
      setGeneratedPlan({
        name: `AI Generated Diet Plan - ${mockPatients.find(p => p.id.toString() === selectedPatient)?.name}`,
        duration: duration[0],
        calories: calories[0],
        meals: {
          breakfast: [
            "Warm Oats with Almonds and Honey",
            "Herbal Tea (Ginger-Cardamom)"
          ],
          lunch: [
            "Quinoa Bowl with Seasonal Vegetables",
            "Cucumber Mint Raita",
            "Brown Rice"
          ],
          dinner: [
            "Moong Dal Soup",
            "Steamed Vegetables",
            "Chapati (1 piece)"
          ],
          snacks: includeSnacks ? [
            "Mixed Nuts (handful)",
            "Herbal Tea"
          ] : []
        },
        supplements: includeSuplements ? [
          "Triphala (before bed)",
          "Ashwagandha (morning)"
        ] : [],
        guidelines: [
          "Eat meals at consistent times",
          "Chew food thoroughly",
          "Avoid cold drinks with meals",
          "Practice mindful eating"
        ]
      });
      setIsGenerating(false);
    }, 3000);
  };

  const savePlan = () => {
    console.log('Saving generated plan...');
  };

  const downloadPlan = () => {
    console.log('Downloading plan...');
  };

  const regeneratePlan = () => {
    setGeneratedPlan(null);
    handleGenerate();
  };

  const getPatientInfo = () => {
    return mockPatients.find(p => p.id.toString() === selectedPatient);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl text-foreground">Auto Generate Diet</h1>
          <p className="text-muted-foreground">Create personalized diet plans using AI recommendations</p>
        </div>
        <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
          <Wand2 className="w-6 h-6 text-primary" />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Configuration Panel */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <Settings className="w-5 h-5 mr-2 text-primary" />
              Diet Plan Configuration
            </CardTitle>
            <CardDescription>
              Set parameters for AI-generated diet recommendations
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Patient Selection */}
            <div className="space-y-2">
              <Label htmlFor="patient">Select Patient</Label>
              <Select value={selectedPatient} onValueChange={setSelectedPatient}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a patient" />
                </SelectTrigger>
                <SelectContent>
                  {mockPatients.map((patient) => (
                    <SelectItem key={patient.id} value={patient.id.toString()}>
                      <div className="flex items-center space-x-2">
                        <span>{patient.name}</span>
                        <Badge variant="outline" className="text-xs">
                          {patient.dosha}
                        </Badge>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {selectedPatient && (
                <div className="p-3 bg-muted rounded-lg text-sm">
                  <div className="flex items-center space-x-4">
                    <span>Age: {getPatientInfo()?.age}</span>
                    <span>Condition: {getPatientInfo()?.condition}</span>
                    <Badge className="text-xs">
                      {getPatientInfo()?.dosha}
                    </Badge>
                  </div>
                </div>
              )}
            </div>

            {/* Diet Goal */}
            <div className="space-y-2">
              <Label htmlFor="goal">Diet Goal</Label>
              <Select value={dietGoal} onValueChange={setDietGoal}>
                <SelectTrigger>
                  <SelectValue placeholder="Select primary goal" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="weight-loss">Weight Loss</SelectItem>
                  <SelectItem value="weight-gain">Weight Gain</SelectItem>
                  <SelectItem value="digestive-health">Digestive Health</SelectItem>
                  <SelectItem value="energy-boost">Energy Boost</SelectItem>
                  <SelectItem value="detox">Detoxification</SelectItem>
                  <SelectItem value="immunity">Immunity Boost</SelectItem>
                  <SelectItem value="pregnancy">Pregnancy Support</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Duration */}
            <div className="space-y-2">
              <Label>Duration: {duration[0]} days</Label>
              <Slider
                value={duration}
                onValueChange={setDuration}
                max={90}
                min={7}
                step={7}
                className="w-full"
              />
              <div className="flex justify-between text-sm text-muted-foreground">
                <span>7 days</span>
                <span>90 days</span>
              </div>
            </div>

            {/* Daily Calories */}
            <div className="space-y-2">
              <Label>Daily Calories: {calories[0]} kcal</Label>
              <Slider
                value={calories}
                onValueChange={setCalories}
                max={3000}
                min={1000}
                step={100}
                className="w-full"
              />
              <div className="flex justify-between text-sm text-muted-foreground">
                <span>1000 kcal</span>
                <span>3000 kcal</span>
              </div>
            </div>

            {/* Meal Complexity */}
            <div className="space-y-2">
              <Label>Meal Complexity</Label>
              <Select value={mealComplexity} onValueChange={setMealComplexity}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="simple">Simple (15-20 min prep)</SelectItem>
                  <SelectItem value="medium">Medium (30-45 min prep)</SelectItem>
                  <SelectItem value="complex">Complex (60+ min prep)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Dietary Restrictions */}
            <div className="space-y-2">
              <Label htmlFor="restrictions">Dietary Restrictions (Optional)</Label>
              <Textarea
                id="restrictions"
                placeholder="e.g., No dairy, gluten-free, vegetarian..."
                value={restrictions}
                onChange={(e) => setRestrictions(e.target.value)}
                rows={3}
              />
            </div>

            {/* Options */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label htmlFor="snacks">Include Snacks</Label>
                <Switch
                  id="snacks"
                  checked={includeSnacks}
                  onCheckedChange={setIncludeSnacks}
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="supplements">Include Supplements</Label>
                <Switch
                  id="supplements"
                  checked={includeSuplements}
                  onCheckedChange={setIncludeSupplements}
                />
              </div>
            </div>

            {/* Generate Button */}
            <Button 
              onClick={handleGenerate}
              disabled={!selectedPatient || !dietGoal || isGenerating}
              className="w-full bg-primary hover:bg-primary/90"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Zap className="w-4 h-4 mr-2" />
                  Generate Diet Plan
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Generated Plan Preview */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <Target className="w-5 h-5 mr-2 text-primary" />
              Generated Plan Preview
            </CardTitle>
            <CardDescription>
              AI-generated personalized diet recommendations
            </CardDescription>
          </CardHeader>
          <CardContent>
            {!generatedPlan && !isGenerating && (
              <div className="text-center py-12">
                <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
                  <Wand2 className="w-8 h-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg text-muted-foreground mb-2">No plan generated yet</h3>
                <p className="text-sm text-muted-foreground">
                  Configure the parameters and click generate to create a diet plan
                </p>
              </div>
            )}

            {isGenerating && (
              <div className="text-center py-12">
                <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <RefreshCw className="w-8 h-8 text-primary animate-spin" />
                </div>
                <h3 className="text-lg text-foreground mb-2">Generating Your Plan</h3>
                <p className="text-sm text-muted-foreground">
                  Analyzing patient profile and creating personalized recommendations...
                </p>
              </div>
            )}

            {generatedPlan && (
              <div className="space-y-6">
                {/* Plan Header */}
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-lg">{generatedPlan.name}</h3>
                    <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                      <span className="flex items-center">
                        <Calendar className="w-3 h-3 mr-1" />
                        {generatedPlan.duration} days
                      </span>
                      <span className="flex items-center">
                        <Target className="w-3 h-3 mr-1" />
                        {generatedPlan.calories} kcal/day
                      </span>
                    </div>
                  </div>
                  <Badge variant="default" className="bg-green-100 text-green-800">
                    <CheckCircle className="w-3 h-3 mr-1" />
                    Generated
                  </Badge>
                </div>

                {/* Meals Preview */}
                <div className="space-y-4">
                  <h4 className="text-sm">Sample Daily Meals:</h4>
                  
                  {Object.entries(generatedPlan.meals).map(([mealType, items]) => (
                    items.length > 0 && (
                      <div key={mealType} className="p-3 border rounded-lg">
                        <h5 className="text-sm capitalize mb-2">{mealType}:</h5>
                        <ul className="text-sm text-muted-foreground space-y-1">
                          {items.map((item, index) => (
                            <li key={index}>• {item}</li>
                          ))}
                        </ul>
                      </div>
                    )
                  ))}
                </div>

                {/* Supplements */}
                {generatedPlan.supplements.length > 0 && (
                  <div className="p-3 border rounded-lg">
                    <h5 className="text-sm mb-2">Recommended Supplements:</h5>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      {generatedPlan.supplements.map((supplement, index) => (
                        <li key={index}>• {supplement}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Guidelines */}
                <div className="p-3 border rounded-lg">
                  <h5 className="text-sm mb-2">Guidelines:</h5>
                  <ul className="text-sm text-muted-foreground space-y-1">
                    {generatedPlan.guidelines.map((guideline, index) => (
                      <li key={index}>• {guideline}</li>
                    ))}
                  </ul>
                </div>

                {/* Actions */}
                <div className="flex items-center space-x-2">
                  <Button onClick={savePlan} className="flex-1">
                    <Save className="w-4 h-4 mr-2" />
                    Save Plan
                  </Button>
                  <Button onClick={downloadPlan} variant="outline">
                    <Download className="w-4 h-4" />
                  </Button>
                  <Button onClick={regeneratePlan} variant="outline">
                    <RefreshCw className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}