import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card";
import { Button } from "./ui/button";
import { Label } from "./ui/label";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "./ui/select";
import { RefreshCw, Target, Wand2, Download } from "lucide-react";

export function AutoGenerateDiet() {
  const [prakriti, setPrakriti] = useState("");
  const [dosha, setDosha] = useState("none");
  const [calories, setCalories] = useState(2000);
  const [isGenerating, setIsGenerating] = useState(false);
  const [diet, setDiet] = useState<any | null>(null);

  // --------------------- GENERATE DIET ---------------------
  const handleGenerate = async () => {
    if (!prakriti) {
      alert("Please select prakriti");
      return;
    }

    setIsGenerating(true);
    setDiet(null);

    try {
      const AI_API_URL = import.meta.env.VITE_AI_API_URL || "http://localhost:8000";
      const res = await fetch(`${AI_API_URL}/generate-diet`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prakriti,
          dosha: dosha === "none" ? "" : dosha,
          daily_calorie_target: calories,
        }),
      });

      const data = await res.json();
      console.log("API response:", data);

      setDiet(data.diet_plan); // IMPORTANT: use diet_plan not diet
    } catch (err) {
      console.error(err);
      alert("Failed to generate diet plan");
    } finally {
      setIsGenerating(false);
    }
  };

  // --------------------- PDF DOWNLOAD ---------------------
  const handleDownloadPDF = () => {
    if (!diet) return;

    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("7-Day Ayurvedic Diet Plan", 14, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Prakriti: ${prakriti}`, 14, 30);
    doc.text(`Dosha: ${dosha === "none" ? "None" : dosha}`, 14, 38);
    doc.text(`Calories: ${calories} kcal/day`, 14, 46);

    let startY = 55;

    Object.entries(diet).forEach(([day, meals]: any) => {
      if (startY > 250) {
        doc.addPage();
        startY = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(`Day ${day}`, 14, startY);
      startY += 6;

      ["breakfast", "lunch", "dinner"].forEach((mealType) => {
        const rows = meals[mealType].map((item: any) => [
          item.food,
          `${item.calories} kcal`,
          `${item.protein}g`,
          `${item.carbs}g`,
          `${item.fat}g`,
        ]);

        autoTable(doc, {
          startY,
          head: [[mealType.toUpperCase(), "KCAL", "P", "C", "F"]],
          body: rows,
          theme: "grid",
          headStyles: { fillColor: [40, 80, 60], textColor: 255, fontSize: 10 },
          bodyStyles: { fontSize: 9 },
          margin: { left: 14, right: 14 },
        });

        // @ts-ignore
        startY = doc.lastAutoTable.finalY + 6;
      });

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(
        `Totals: ${meals.totals.calories} kcal | P:${meals.totals.protein}g | C:${meals.totals.carbs}g | F:${meals.totals.fat}g`,
        14,
        startY
      );

      startY += 12;
    });

    doc.save("ayurvedic_diet_plan.pdf");
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-semibold">Auto Generate Diet</h1>
          <p className="text-muted-foreground">
            7-day personalized Ayurvedic diet based on prakriti & dosha.
          </p>
        </div>
        <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
          <Wand2 className="w-6 h-6 text-primary" />
        </div>
      </div>

      {/* Input Card */}
      <Card>
        <CardHeader>
          <CardTitle>Configuration</CardTitle>
          <CardDescription>
            Choose prakriti, imbalance, and calorie target.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Prakriti */}
          <div className="space-y-2">
            <Label>Prakriti</Label>
            <Select value={prakriti} onValueChange={setPrakriti}>
              <SelectTrigger>
                <SelectValue placeholder="Select prakriti" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Vata">Vata</SelectItem>
                <SelectItem value="Pitta">Pitta</SelectItem>
                <SelectItem value="Kapha">Kapha</SelectItem>
                <SelectItem value="Vata-Pitta">Vata-Pitta</SelectItem>
                <SelectItem value="Vata-Kapha">Vata-Kapha</SelectItem>
                <SelectItem value="Pitta-Kapha">Pitta-Kapha</SelectItem>
                <SelectItem value="Vata-Pitta-Kapha">Vata-Pitta-Kapha</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Dosha */}
          <div className="space-y-2">
            <Label>Dosha imbalance</Label>
            <Select value={dosha} onValueChange={setDosha}>
              <SelectTrigger>
                <SelectValue placeholder="Select imbalance" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">None / General</SelectItem>
                <SelectItem value="V">Vata</SelectItem>
                <SelectItem value="P">Pitta</SelectItem>
                <SelectItem value="K">Kapha</SelectItem>
                <SelectItem value="VP">Vata + Pitta</SelectItem>
                <SelectItem value="VK">Vata + Kapha</SelectItem>
                <SelectItem value="PK">Pitta + Kapha</SelectItem>
                <SelectItem value="VPK">Vata + Pitta + Kapha</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Calories */}
          <div className="space-y-2">
            <Label>Daily calories</Label>
            <input
              type="number"
              min={1200}
              max={3500}
              value={calories}
              onChange={(e) => setCalories(Number(e.target.value))}
              className="w-full border rounded-md px-3 py-2"
            />
          </div>

          {/* Generate Button */}
          <Button className="w-full" onClick={handleGenerate} disabled={isGenerating}>
            {isGenerating ? (
              <>
                <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <Target className="w-4 h-4 mr-2" />
                Generate Diet
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Output */}
      {diet && (
        <Card>
          <CardHeader className="flex justify-between items-center">
            <CardTitle>7-Day Diet Plan</CardTitle>
            <Button onClick={handleDownloadPDF}>
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
          </CardHeader>
          <CardContent className="space-y-6">
            {Object.entries(diet).map(([day, meals]: any) => (
              <div key={day} className="border rounded-lg p-4 bg-card">
                <h2 className="text-xl font-semibold">Day {day}</h2>

                {["breakfast", "lunch", "dinner"].map((mealKey) => (
                  <div key={mealKey} className="mt-4">
                    <h3 className="font-medium capitalize">{mealKey}</h3>
                    <div className="bg-muted p-3 rounded-md space-y-1">
                      {meals[mealKey].map((item: any, idx: number) => (
                        <p key={idx} className="text-sm">
                          • {item.food}{" "}
                          <span className="text-xs text-muted-foreground">
                            ({item.calories} kcal — P:{item.protein}g, C:{item.carbs}g, F:{item.fat}g)
                          </span>
                        </p>
                      ))}
                    </div>
                  </div>
                ))}

                <div className="bg-primary/10 p-3 mt-4 rounded-md">
                  <p className="font-semibold text-sm">
                    Totals: {meals.totals.calories} kcal | P:
                    {meals.totals.protein}g | C:{meals.totals.carbs}g | F:
                    {meals.totals.fat}g
                  </p>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
