# -*- coding: utf-8 -*-
"""RF_MODEL_full_dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YflmaQ7674oNphVbGXKlrT3ooqMe7Nla
"""

# ======= food_suitability_training.py =======
import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import classification_report, hamming_loss, accuracy_score

# ---- Config / paths ----
CLEANED_CSV = "/content/merged_master_cleaned.xlsx"   # path to CSV
SAVE_PIPELINE_PATH = "/content/food_suitability_pipeline_full.joblib"
RANDOM_STATE = 42
N_ESTIMATORS = 300
TEST_SIZE = 0.20

# ---- 1) Load cleaned data ----
df = pd.read_excel(CLEANED_CSV)
print("Loaded cleaned data:", df.shape)

# ---- 2) Identify feature groups ----
# Numeric columns (these should exist)
num_cols = [c for c in ["calories", "protein", "carbs", "fat"] if c in df.columns]
# Multi-hot columns (rasa__, virya__, guna__, vipaka__ generated during cleaning)
multi_hot_prefixes = ["rasa__", "virya__", "guna__", "vipaka__"]
multi_hot_cols = [c for c in df.columns if any(c.startswith(pref) for pref in multi_hot_prefixes)]
# Category column (one-hot via encoder)
cat_col = "category" if "category" in df.columns else None

print("Numeric cols:", num_cols)
print("Multi-hot cols (#):", len(multi_hot_cols))
print("Category col:", cat_col)

#---- 3) Define X and y ----
target_cols = ["pacify_vata", "pacify_pitta", "pacify_kapha"]
for t in target_cols:
    if t not in df.columns:
        raise ValueError(f"Missing target column: {t}")

# Features: numeric + multi-hot + category (category will be encoded by pipeline)
feature_cols = num_cols + multi_hot_cols + ([cat_col] if cat_col else [])
X = df[feature_cols].copy()
y = df[target_cols].astype(int).copy()

print("Feature matrix shape:", X.shape, "Target shape:", y.shape)

# ---- 4) Build preprocessing pipeline ----
# Numeric pipeline: impute (mean) -> scale
num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

# Category pipeline: impute missing -> one-hot encode, ignore unknowns
if cat_col:
    cat_pipe = Pipeline([
        ("impute", SimpleImputer(strategy="constant", fill_value="__missing__")),
        ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

# ColumnTransformer: apply numeric pipe to numeric cols, cat pipe to category, passthrough multi-hot (already numeric)
transformers = []
if num_cols:
    transformers.append(("num", num_pipe, num_cols))
if cat_col:
    transformers.append(("cat", cat_pipe, [cat_col]))

preprocessor = ColumnTransformer(transformers, remainder="passthrough", sparse_threshold=0)

# ---- 5) Build final pipeline with multi-output RF ----
rf = RandomForestClassifier(n_estimators=N_ESTIMATORS, random_state=RANDOM_STATE, n_jobs=-1)
multi_rf = MultiOutputClassifier(rf)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("clf", multi_rf)
])

# ---- 6) Train/test split ----
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE)
print("Train / test shapes:", X_train.shape, X_test.shape)

# ---- 7) Fit pipeline ----
print("Training... (this may take a bit)")
pipeline.fit(X_train, y_train)
print("Training done.")

# ---- 8) Evaluate ----
y_pred = pipeline.predict(X_test)

print("\n--- Overall metrics ---")
print("Subset accuracy (default .score):", pipeline.score(X_test, y_test))
print("Hamming loss (lower is better):", hamming_loss(y_test, y_pred))

print("\n--- Per-label classification reports ---")
# y_test / y_pred are arrays/dataframes — ensure proper format
y_test_arr = np.asarray(y_test)
y_pred_arr = np.asarray(y_pred)
for i, col in enumerate(target_cols):
    print(f"\nLabel: {col}")
    print(classification_report(y_test_arr[:, i], y_pred_arr[:, i], digits=4))

# ---- 9) Feature importance (approx) ----
# We want to map feature importances back to original feature names.
# First, obtain the preprocessor's output feature names.

def get_feature_names_from_column_transformer(ct, input_features):
    """Return list of feature names after ColumnTransformer transform (scikit-learn >=0.23)."""
    feature_names = []

    # If transformer's remainder='passthrough', the passthrough columns will be appended.
    for name, trans, cols in ct.transformers_:
        if name == "remainder":
            continue
        if hasattr(trans, 'named_steps') and 'ohe' in trans.named_steps:
            # OneHotEncoder inside pipeline
            ohe = trans.named_steps['ohe']
            # get categories in order and build names
            cats = ohe.categories_
            cols_out = []
            for i, orig in enumerate(cols):
                cat_names = [f"{orig}__{str(c)}" for c in cats[i]]
                cols_out.extend(cat_names)
            feature_names.extend(cols_out)
        else:
            # for numeric pipeline, keep original column names
            feature_names.extend(list(cols))

    # handle remainder (passthrough) columns
    if ct.remainder == "passthrough":
        # determine which columns are passthrough
        used_cols = []
        for _, _, cols in ct.transformers_:
            if cols == "remainder":
                continue
            if isinstance(cols, list):
                used_cols.extend(cols)
        # all input features minus used_cols
        passthrough = [c for c in input_features if c not in used_cols]
        feature_names.extend(passthrough)

    return feature_names

# Build input_features list that matches X columns order
input_features = feature_cols.copy()
feat_names = get_feature_names_from_column_transformer(preprocessor, input_features)
print("\nTotal transformed feature count:", len(feat_names))

# Extract feature importances from each estimator (one per target)
# MultiOutputClassifier stores estimators_ as list of estimators (one per label)
estimators = pipeline.named_steps["clf"].estimators_
importances = []
for est in estimators:
    # est is a RandomForestClassifier
    importances.append(est.feature_importances_)

# Convert to DataFrame and compute average importance across outputs
imp_df = pd.DataFrame(importances).T
imp_df.columns = target_cols
if len(feat_names) == imp_df.shape[0]:
    imp_df["feature"] = feat_names
    # compute mean importance and sort
    imp_df["mean_importance"] = imp_df[target_cols].mean(axis=1)
    imp_df = imp_df.sort_values("mean_importance", ascending=False).reset_index(drop=True)
    print("\nTop 30 features by mean importance:")
    print(imp_df[["feature","mean_importance"]].head(30).to_string(index=False))
else:
    print("Warning: feature name count does not match importances length. Skipping named importances.")
    print("Importances shape:", imp_df.shape, "Feature names:", len(feat_names))

# ---- 10) Save pipeline ----
joblib.dump(pipeline, SAVE_PIPELINE_PATH)
print("\nSaved trained pipeline to:", SAVE_PIPELINE_PATH)

# ---- 11) Example: how to predict for new foods (usage snippet) ----
print("""
--- USAGE EXAMPLE ---
# Load pipeline: pipeline = joblib.load('/path/to/food_suitability_pipeline.joblib')
# Prepare a DataFrame 'X_new' with columns equal to feature_cols:
# numeric cols (calories, protein, carbs, fat), multi-hot columns (rasa__*, virya__*, ...),
# and a 'category' column (string) if used. For multi-hot tokens absent in new row, put 0.
# Then:
probs = pipeline.predict_proba(X_new)   # returns list-of-arrays for MultiOutputClassifier
# probs[i][:,1] is probability of label i being 1 (pacify)
# pipeline.predict(X_new) gives final binary predictions per label.
""")
# End of script



# ======= Merge: model-driven diet generator (paste into notebook) =======
import pandas as pd
import numpy as np
import joblib
import random

# ---------- Config (edit if necessary) ----------
CLEANED_CSV = "/content/merged_master_cleaned.xlsx"  # cleaned dataset from earlier
PIPELINE_PATH = "/content/food_suitability_pipeline_full.joblib"  # saved pipeline from training code
PROB_THRESHOLD = 0.5   # threshold to treat prob->binary if needed
RANDOM_STATE = 42
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ---------- Load data & model ----------
foods = pd.read_excel(CLEANED_CSV)
pipeline = joblib.load(PIPELINE_PATH)

# Ensure key columns for printing exist
for col in ["food","calories","protein","carbs","fat"]:
    if col not in foods.columns:
        raise ValueError(f"Required column missing in cleaned CSV: {col}")

# Build list of features expected by pipeline (same as used when training)
# NOTE: pipeline expects columns in training feature set. We'll provide a DataFrame with the same columns.
# For simplicity we will use numeric cols + multi-hot columns already present + category.
# Build X_all by selecting numeric + multi-hot + category (if present)
num_cols = [c for c in ["calories","protein","carbs","fat"] if c in foods.columns]
multi_hot_cols = [c for c in foods.columns if any(c.startswith(pref) for pref in ["rasa__", "virya__", "guna__", "vipaka__"])]
cat_col = "category" if "category" in foods.columns else None
feature_cols = num_cols + multi_hot_cols + ([cat_col] if cat_col else [])

X_all = foods[feature_cols].copy()

# ---------- Compute model probabilities for pacify labels ----------
# For MultiOutputClassifier pipeline, predict_proba returns list of arrays per label.
proba_list = pipeline.predict_proba(X_all)  # list length 3, each array (n_samples, n_classes)

# Extract probability of class '1' (pacify) for each label
# proba_list[0] -> [[p0_pred0, p0_pred1], ...] for label0
n = X_all.shape[0]
prob_arr = np.zeros((n, 3))
for i, arr in enumerate(proba_list):
    # arr[:,1] is probability of label==1
    prob_arr[:, i] = arr[:, 1]

foods["prob_vata"] = prob_arr[:, 0]
foods["prob_pitta"] = prob_arr[:, 1]
foods["prob_kapha"] = prob_arr[:, 2]

# Optional: predicted binary flags (if you want to use a hard filter)
foods["pred_pacify_vata"] = (foods["prob_vata"] >= PROB_THRESHOLD).astype(int)
foods["pred_pacify_pitta"] = (foods["prob_pitta"] >= PROB_THRESHOLD).astype(int)
foods["pred_pacify_kapha"] = (foods["prob_kapha"] >= PROB_THRESHOLD).astype(int)

#---------- Prakriti weights (example / tunable) ----------
# These give a small bonus/penalty to foods that pacify certain doshas given patient's prakriti.
# Negative value means foods that pacify that dosha are *less* preferred for this prakriti (rare),
# Positive means preferred.
prakriti_weights = {
    "Vata":         {"vata": 1.2,  "pitta": 0.2, "kapha": 0.6},
    "Pitta":        {"vata": 0.6,  "pitta": 1.2, "kapha": 0.3},
    "Kapha":        {"vata": 0.7,  "pitta": 0.3, "kapha": 1.2},
    "Vata-Pitta":   {"vata": 1.0,  "pitta": 1.0, "kapha": 0.3},
    "Vata-Kapha":   {"vata": 1.0,  "pitta": 0.3, "kapha": 1.0},
    "Pitta-Kapha":  {"vata": 0.3,  "pitta": 1.0, "kapha": 1.0},
    "Vata-Pitta-Kapha": {"vata": 0.9, "pitta": 0.9, "kapha": 0.9}
}
# Ensure keys match user input style (case-insensitive)
def normalize_prakriti(s):
    return s.strip().title().replace(" ", "-")

# ---------- Scoring function ----------
def score_food_row(row, patient_prakriti, needed_doshas, calorie_target_remaining, used_counts):
    """
    row: a pandas Series for one food row (must contain prob_vata/prob_pitta/prob_kapha, calories)
    patient_prakriti: normalized string like "Vata" or "Vata-Pitta"
    needed_doshas: list like ['v','p'] or [] (means maintenance)
    calorie_target_remaining: numeric, used to prefer foods near target per item
    used_counts: dict mapping food->times already used this week (penalty for repeats)
    returns: float score (higher = better)
    """
    # Model probability component: multiply probabilities for required doshas (product) to prefer foods that pacify all requested doshas.
    if needed_doshas:
        p_model = 1.0
        for d in needed_doshas:
            if d.lower() == 'v':
                p_model *= float(row["prob_vata"])
            elif d.lower() == 'p':
                p_model *= float(row["prob_pitta"])
            elif d.lower() == 'k':
                p_model *= float(row["prob_kapha"])
    else:
        # maintenance: average of probs (prefer generally balancing foods)
        p_model = float((row["prob_vata"] + row["prob_pitta"] + row["prob_kapha"]) / 3.0)

    # Prakriti bonus (simple linear combination)
    p = prakriti_weights.get(patient_prakriti, {"vata":0,"pitta":0,"kapha":0})
    prakriti_score = p["vata"]*row["prob_vata"] + p["pitta"]*row["prob_pitta"] + p["kapha"]*row["prob_kapha"]
# Nutrition proximity: we want food calories to be reasonable for a meal item
    # Use a heuristic: prefer items whose calories are near meal target portion
    cal = float(row["calories"]) if not pd.isna(row["calories"]) else 0.0
    # small gaussian-like preference around target/4 (if item size unknown)
    if calorie_target_remaining > 0:
        target_item = max(30.0, calorie_target_remaining / 3.5)  # heuristic
    else:
        target_item = 100.0
    nut_score = np.exp(-abs(cal - target_item) / (target_item + 1.0))
    # repeat penalty
    repeat_pen = used_counts.get(row["food"], 0)

    # combine (weights tunable)
    score = 2.0 * p_model + 1.0 * prakriti_score + 0.8 * nut_score - 1.5 * repeat_pen
    return score

# ---------- Filtering function that uses model predictions (soft) ----------
def filter_by_dosha_model(df, dosha_text, mode="soft", prob_threshold=PROB_THRESHOLD):
    """
    df: foods dataframe with prob_vata/prob_pitta/prob_kapha
    dosha_text: like 'V', 'VP', 'VPK', '' (empty means maintenance)
    mode: "soft" -> keep full df (we'll score by probabilities), "hard" -> filter rows where predicted pacify flag >= threshold
    """
    t = str(dosha_text).upper().replace(" ", "")
    if t == "" or t is None:
        return df.copy()
    mask = pd.Series(True, index=df.index)
    if mode == "hard":
        if "V" in t:
            mask &= (df["pred_pacify_vata"] == 1)
        if "P" in t:
            mask &= (df["pred_pacify_pitta"] == 1)
        if "K" in t:
            mask &= (df["pred_pacify_kapha"] == 1)
        return df[mask].copy()
    else:
        # soft: return full df for scoring (no hard filter)
        return df.copy()

# ---------- Sampling helpers: safe_pick replaced by scorer + greedy pick ----------
def generate_mixed_7_day_diet_model(df, patient_prakriti, needed_doshas, daily_calorie_target=2000):
    """
    df: foods DataFrame with model probs
    patient_prakriti: normalized e.g. "Vata" or "Vata-Pitta"
    needed_doshas: list of 'v','p','k' or empty list for maintenance
    returns: diet dict keyed by day -> {breakfast, lunch, dinner, totals}
    """
    # local copy
    pool_master = df.reset_index(drop=True).copy()
    diet = {}
    used_counts = {}  # track repeats in week

    for day in range(1, 7+1):
        day_meals = {}
        # Define meal calorie split heuristics (can be tuned)
        remaining_daily = daily_calorie_target
        # we choose three meals; approximate item calorie target per meal
        meal_targets = {"breakfast": daily_calorie_target * 0.25, "lunch": daily_calorie_target * 0.45, "dinner": daily_calorie_target * 0.30}

        for meal_name in ["breakfast", "lunch", "dinner"]:
            meal_target = meal_targets[meal_name]
            picks = []
            # We'll pick up to 4 items per meal (same as original)
            local_pool = pool_master.copy()
            for pick_i in range(4):
                # compute scores for each candidate
                local_pool["score"] = local_pool.apply(lambda r: score_food_row(r, patient_prakriti, needed_doshas, meal_target, used_counts), axis=1)
                # sort by score descending
                local_pool_sorted = local_pool.sort_values("score", ascending=False).reset_index(drop=True)
                if local_pool_sorted.empty:
                    break
                # pick top candidate (you may randomize among top-K)
                candidate = local_pool_sorted.iloc[0]
                picks.append(candidate)
                # update used_counts
                used_counts[candidate["food"]] = used_counts.get(candidate["food"], 0) + 1
                # remove that exact food from pool_master for this meal pick to avoid duplicates in same meal
                pool_master = pool_master[pool_master["food"] != candidate["food"]].reset_index(drop=True)
                local_pool = local_pool[local_pool["food"] != candidate["food"]].reset_index(drop=True)
                if local_pool.empty:
                    break

            # convert picks to DataFrame (if empty, create empty df with columns)
            meal_df = pd.DataFrame(picks) if picks else pd.DataFrame(columns=foods.columns)
            day_meals[meal_name] = meal_df

        # compute totals
        totals = {
            "calories": sum(dfm["calories"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "protein": sum(dfm["protein"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "carbs": sum(dfm["carbs"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "fat": sum(dfm["fat"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]])
        }
        day_meals["totals"] = totals
        diet[day] = day_meals

        # After finishing the day, restore pool_master from original df excluding foods with used_counts very high
        # For simplicity, rebuild pool_master from original foods and remove foods used > threshold (e.g., 3 times/week)
        pool_master = df.copy().reset_index(drop=True)
        pool_master = pool_master[~pool_master["food"].isin([f for f,c in used_counts.items() if c > 3])].reset_index(drop=True)

    return diet

# ======= Full: model-driven diet generator + YouTube recipe links =======
import pandas as pd
import numpy as np
import joblib
import random
import io, sys, re
from urllib.parse import quote_plus

# ---------- Config ----------
CLEANED_CSV = "/content/merged_master_cleaned.xlsx"
PIPELINE_PATH = "/content/food_suitability_pipeline_full.joblib"
PROB_THRESHOLD = 0.5
RANDOM_STATE = 42
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ---------- Load data & model ----------
foods = pd.read_excel(CLEANED_CSV)
pipeline = joblib.load(PIPELINE_PATH)

# Ensure key columns exist
for col in ["food","calories","protein","carbs","fat"]:
    if col not in foods.columns:
        raise ValueError(f"Required column missing in cleaned CSV: {col}")

# Build feature set used for prediction (must match training)
num_cols = [c for c in ["calories","protein","carbs","fat"] if c in foods.columns]
multi_hot_cols = [c for c in foods.columns if c.startswith("rasa__") or c.startswith("virya__") or c.startswith("guna__") or c.startswith("vipaka__")]
cat_col = "category" if "category" in foods.columns else None
feature_cols = num_cols + multi_hot_cols + ([cat_col] if cat_col else [])
X_all = foods[feature_cols].copy()

# ---------- Compute model probabilities ----------
proba_list = pipeline.predict_proba(X_all)  # list with 3 arrays (n_samples, n_classes)
n = X_all.shape[0]
prob_arr = np.zeros((n, 3))
for i, arr in enumerate(proba_list):
    prob_arr[:, i] = arr[:, 1]  # probability of class 1 (pacify)

foods["prob_vata"] = prob_arr[:, 0]
foods["prob_pitta"] = prob_arr[:, 1]
foods["prob_kapha"] = prob_arr[:, 2]

foods["pred_pacify_vata"] = (foods["prob_vata"] >= PROB_THRESHOLD).astype(int)
foods["pred_pacify_pitta"] = (foods["prob_pitta"] >= PROB_THRESHOLD).astype(int)
foods["pred_pacify_kapha"] = (foods["prob_kapha"] >= PROB_THRESHOLD).astype(int)

# ---------- Prakriti weights (tunable) ----------
prakriti_weights = {
    "Vata":         {"vata": 1.2,  "pitta": 0.2, "kapha": 0.6},
    "Pitta":        {"vata": 0.6,  "pitta": 1.2, "kapha": 0.3},
    "Kapha":        {"vata": 0.7,  "pitta": 0.3, "kapha": 1.2},
    "Vata-Pitta":   {"vata": 1.0,  "pitta": 1.0, "kapha": 0.3},
    "Vata-Kapha":   {"vata": 1.0,  "pitta": 0.3, "kapha": 1.0},
    "Pitta-Kapha":  {"vata": 0.3,  "pitta": 1.0, "kapha": 1.0},
    "Vata-Pitta-Kapha": {"vata": 0.9, "pitta": 0.9, "kapha": 0.9}
}
def normalize_prakriti(s):
    return s.strip().title().replace(" ", "-")

# ---------- Scoring function ----------
def score_food_row(row, patient_prakriti, needed_doshas, calorie_target_remaining, used_counts):
    # model component
    if needed_doshas:
        p_model = 1.0
        for d in needed_doshas:
            if d.lower() == 'v':
                p_model *= float(row["prob_vata"])
            elif d.lower() == 'p':
                p_model *= float(row["prob_pitta"])
            elif d.lower() == 'k':
                p_model *= float(row["prob_kapha"])
    else:
        p_model = float((row["prob_vata"] + row["prob_pitta"] + row["prob_kapha"]) / 3.0)

    # prakriti component
    p = prakriti_weights.get(patient_prakriti, {"vata":0,"pitta":0,"kapha":0})
    prakriti_score = p["vata"]*row["prob_vata"] + p["pitta"]*row["prob_pitta"] + p["kapha"]*row["prob_kapha"]

    # nutrition proximity
    cal = float(row["calories"]) if (not pd.isna(row["calories"])) else 0.0
    if calorie_target_remaining > 0:
        target_item = max(30.0, calorie_target_remaining / 3.5)
    else:
        target_item = 100.0
    nut_score = np.exp(-abs(cal - target_item) / (target_item + 1.0))

    repeat_pen = used_counts.get(row["food"], 0)

    # combine weighted components (tunable)
    score = 2.0 * p_model + 1.0 * prakriti_score + 0.8 * nut_score - 1.5 * repeat_pen
    return score

# ---------- Filter function (soft/hard) ----------
def filter_by_dosha_model(df, dosha_text, mode="soft", prob_threshold=PROB_THRESHOLD):
    t = str(dosha_text).upper().replace(" ", "")
    if t == "" or t is None:
        return df.copy()
    mask = pd.Series(True, index=df.index)
    if mode == "hard":
        if "V" in t:
            mask &= (df["pred_pacify_vata"] == 1)
        if "P" in t:
            mask &= (df["pred_pacify_pitta"] == 1)
        if "K" in t:
            mask &= (df["pred_pacify_kapha"] == 1)
        return df[mask].copy()
    else:
        return df.copy()

# ---------- Diet generator (model-driven) ----------
def generate_mixed_7_day_diet_model(df, patient_prakriti, needed_doshas, daily_calorie_target=2000):
    pool_master = df.reset_index(drop=True).copy()
    diet = {}
    used_counts = {}
    for day in range(1, 8):
        day_meals = {}
        meal_targets = {"breakfast": daily_calorie_target * 0.25, "lunch": daily_calorie_target * 0.45, "dinner": daily_calorie_target * 0.30}
        for meal_name in ["breakfast", "lunch", "dinner"]:
            meal_target = meal_targets[meal_name]
            picks = []
            local_pool = pool_master.copy()
            for pick_i in range(4):
                local_pool["score"] = local_pool.apply(lambda r: score_food_row(r, patient_prakriti, needed_doshas, meal_target, used_counts), axis=1)
                local_pool_sorted = local_pool.sort_values("score", ascending=False).reset_index(drop=True)
                if local_pool_sorted.empty:
                    break
                candidate = local_pool_sorted.iloc[0]
                picks.append(candidate)
                used_counts[candidate["food"]] = used_counts.get(candidate["food"], 0) + 1
                pool_master = pool_master[pool_master["food"] != candidate["food"]].reset_index(drop=True)
                local_pool = local_pool[local_pool["food"] != candidate["food"]].reset_index(drop=True)
                if local_pool.empty:
                    break
            meal_df = pd.DataFrame(picks) if picks else pd.DataFrame(columns=foods.columns)
            day_meals[meal_name] = meal_df
        totals = {
            "calories": sum(dfm["calories"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "protein": sum(dfm["protein"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "carbs": sum(dfm["carbs"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]]),
            "fat": sum(dfm["fat"].sum() if not dfm.empty else 0 for dfm in [day_meals["breakfast"], day_meals["lunch"], day_meals["dinner"]])
        }
        day_meals["totals"] = totals
        diet[day] = day_meals
        # rebuild pool_master excluding excessively used foods (>3 uses/week)
        pool_master = df.copy().reset_index(drop=True)
        pool_master = pool_master[~pool_master["food"].isin([f for f,c in used_counts.items() if c > 3])].reset_index(drop=True)
    return diet

######################################################
# ---------- AYURVEDIC ATTRIBUTE HELPERS & PRINTING ----------
def get_multi_hot_tokens(row, prefix):
    tokens = []
    for col in row.index:
        if col.startswith(prefix + "__") and (row[col] == 1 or str(row[col]) == "1"):
            token = col[len(prefix)+2:].replace("_", " ")
            tokens.append(token)
    return tokens

def ayurvedic_attrs_for_row(row, max_attr_len=80):
    rasa = get_multi_hot_tokens(row, "rasa")
    virya = get_multi_hot_tokens(row, "virya")
    guna = get_multi_hot_tokens(row, "guna")
    vipaka = get_multi_hot_tokens(row, "vipaka")
    rasa_s = ", ".join(rasa) if rasa else "-"
    virya_s = ", ".join(virya) if virya else "-"
    guna_s = ", ".join(guna) if guna else "-"
    vipaka_s = ", ".join(vipaka) if vipaka else "-"
    #dosha_text = row.get("dosha_suitable", "") if "dosha_suitable" in row.index else "-"
    #dosha_text = dosha_text if isinstance(dosha_text, str) and dosha_text.strip() else "-"
    combined = f"Rasa: {rasa_s} | Virya: {virya_s} | Guna: {guna_s} | Vipaka: {vipaka_s}"
    if max_attr_len and len(combined) > max_attr_len:
        return combined[:max_attr_len-3] + "..."
    return combined

def print_chart_with_ayurveda(diet, max_attr_len=80):
    for day, meals in diet.items():
        print("\n" + "="*34)
        print(f"          Day {day}")
        print("="*34)
        for meal_name in ["breakfast", "lunch", "dinner"]:
            print(f"\n--- {meal_name.capitalize()} ---")
            mdf = meals[meal_name]
            if mdf is None or mdf.empty:
                print("  (no items)")
                continue
            header = f"{'Food':36s} {'Cal':>6s} {'Prot':>6s} {'Carb':>6s} {'Fat':>6s}   Ayurvedic"
            print(header)
            print("-"*len(header))
            for _, item in mdf.iterrows():
                food_name = str(item.get("food",""))[:36]
                cal = item.get("calories", 0.0) or 0.0
                prot = item.get("protein", 0.0) or 0.0
                carb = item.get("carbs", 0.0) or 0.0
                fat = item.get("fat", 0.0) or 0.0
                attrs = ayurvedic_attrs_for_row(item, max_attr_len=max_attr_len)
                print(f"{food_name:36s} {cal:6.1f} {prot:6.1f} {carb:6.1f} {fat:6.1f}   {attrs}")
        totals = meals.get("totals", {})
        print("\n--- Daily Nutritional Totals ---")
        print(f"Calories: {totals.get('calories',0):.2f}")
        print(f"Protein : {totals.get('protein',0):.2f} g")
        print(f"Carbs   : {totals.get('carbs',0):.2f} g")
        print(f"Fat     : {totals.get('fat',0):.2f} g")


#----------------------------------------------------
# ---------- Pretty-print function ----------
def print_chart(diet):
    for day, meals in diet.items():
        print("\n==============================")
        print(f"          Day {day}")
        print("==============================")
        for meal_name in ["breakfast", "lunch", "dinner"]:
            print(f"\n--- {meal_name.capitalize()} ---")
            mdf = meals[meal_name]
            if mdf is None or mdf.empty:
                print("  (no items)")
                continue
            for _, item in mdf.iterrows():
                print(f"{item['food']} | Cal: {item['calories']:.1f} | Protein: {item['protein']:.1f} | Carbs: {item['carbs']:.1f} | Fat: {item['fat']:.1f}")
        totals = meals["totals"]
        print("\n--- Daily Nutritional Totals ---")
        print(f"Calories: {totals['calories']:.2f}")
        print(f"Protein : {totals['protein']:.2f} g")
        print(f"Carbs   : {totals['carbs']:.2f} g")
        print(f"Fat     : {totals['fat']:.2f} g")

# ---------- Ingredient extractor & YouTube link generator ----------
def extract_ingredients_from_diet_chart(diet_text: str):
    ingredients = []
    seen = set()
    for line in diet_text.splitlines():
        line = line.strip()
        if "| Cal:" in line or "| Cal:" in line.replace("Cal:", "Cal:"):
            # take left part before '| Cal:'
            left = line.split("| Cal:")[0].strip() if "| Cal:" in line else line.split("| Cal:")[0].strip()
            if "(" in left:
                left = left.split("(")[0].strip()
            ing = left.lower()
            if ing and ing not in seen:
                seen.add(ing)
                ingredients.append(ing)
    return ingredients

def get_recipe_youtube_link(ingredient: str):
    query = quote_plus(f"{ingredient} healthy recipe")
    youtube_search_url = f"https://www.youtube.com/results?search_query={query}"
    recipe_name = f"{ingredient.title()} Recipe"
    return {
        "ingredient": ingredient,
        "recipe_name": recipe_name,
        "youtube_link": youtube_search_url
    }

def get_recipes_from_diet_chart(diet_text: str):
    ingredients = extract_ingredients_from_diet_chart(diet_text)
    recipe_suggestions = []
    for ing in ingredients:
        recipe_suggestions.append(get_recipe_youtube_link(ing))
    return recipe_suggestions

# ---------- Run: set inputs and generate ----------
# Interactive: uncomment to accept live input
prakriti_input = input("Enter patient prakriti (Vata, Pitta, Kapha, Vata-Pitta, Vata-Kapha, Pitta-Kapha, Vata-Pitta-Kapha): ")
doctor_input = input("Enter patient dosha imbalance (V, P, K, VP, PK, VK, VPK) or press Enter for maintenance: ")

# Example (non-interactive) - replace with actual user input if desired
# prakriti_input = "Vata"         # e.g., "Vata" or "Vata-Pitta"
# doctor_input = "V"              # e.g., "V", "VP", or "" for maintenance
daily_calorie_target = 2000

patient_prakriti = normalize_prakriti(prakriti_input)
df_for_generation = filter_by_dosha_model(foods, doctor_input, mode="soft")

diet_chart = generate_mixed_7_day_diet_model(df_for_generation, patient_prakriti, list(doctor_input.lower()), daily_calorie_target=daily_calorie_target)

# Print diet
print_chart(diet_chart)

# print with ayurvedic attributes
print_chart_with_ayurveda(diet_chart, max_attr_len=100)

# Capture printed chart into text
buffer = io.StringIO()
old_stdout = sys.stdout
sys.stdout = buffer
print_chart(diet_chart)
sys.stdout = old_stdout
diet_chart_text = buffer.getvalue()

# Show first 500 chars for sanity
print("\n\n--- Preview of diet text (first 500 chars) ---\n")
print(diet_chart_text[:500])

# ---------- Generate recipe suggestions (YouTube search links) ----------
recipe_data = get_recipes_from_diet_chart(diet_chart_text)

# Print first 20 recipe suggestions
print("\n\n--- Recipe suggestions (first 20) ---\n")
for r in recipe_data[:20]:
    print(f"{r['recipe_name']} -> {r['youtube_link']}")

# recipe_data contains all ingredient recipe links and can be saved or used downstream

import joblib
from google.colab import files

# Save and download ML model
joblib.dump(pipeline, "diet_model.joblib")
files.download("diet_model.joblib")